# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

#[[main]]
#identifier = "document"
#name = "文档"
#url = "/document/"
#[main.params]
#icon = "home"
#newtab = false


[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/Iden9"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com"

[social.params]
icon = "brand-twitter"

[[social]]
identifier = "bilibili"
name = "Bilibili"
url = "https://space.bilibili.com/3546774092384417?spm_id_from=333.1007.0.0"

[social.params]
icon = "bilibili"

[[social]]
identifier = "tiktok"
name = "Tiktok"
url = "https://www.douyin.com/"

[social.params]
icon = "tiktok"