# on: push

# jobs:
#     hugo-build:
#         runs-on: ubuntu-latest
#         steps:
#         - run: pwd
#         - run: ls
    # job1:
    #     runs-on: ubuntu-latest
    #     steps:
    #     - run: pwd
    #     - run: ls         
    # job2:
    #     runs-on: windows-latest
    #     steps:
    #     - run: node --versionname: Hugo Build

name: Hugo Build

on: 
  push:

jobs:
  hugo-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)

      - name: Verify Homebrew Installation
        run: |
          brew --version

      - name: Install Hugo Extended
        run: |
          brew install hugo

      - name: Verify Hugo Installation
        run: |
          hugo version

      - name: Build Hugo site
        run: |
          hugo

      - name: List files
        run: ls -al
